version: "3"

services:
  nexus:
    image: sonatype/nexus3:3.0.2
    container_name: nexus 
    ports:
      - "8081:8081"
    networks:
      - nexusnet
    volumes:
      - nexus-data:/nexus-data

networks:
  nexusnet:
    driver: bridge

volumes:
  nexus-data: